[project]
name = "typesafeai-information-extraction-demo"
version = "0.1.0"
description = "Minimal TypeSafe AI text-to-knowledge-graph demo"
readme = "README.md"
authors = [
    { name = "Dzmitry Ashkinadze", email = "dzmitry.ashkinadze@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "en-core-web-sm",
    "pydantic>=2",
    "python-dotenv>=1.2.3",
    "pyvis>=0.3.2",
    "spacy>=3.8.16",
    "typesafe-sdk>=0.7.0",
]

[project.scripts]
typesafeai-information-extraction-demo = "typesafeai_information_extraction_demo:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
